#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
compatibility_date = "<TBD>"
pages_build_output_dir = "./dist/analog/public"

# Check the documentation to configure your worker:
# - https://developers.cloudflare.com/workers/wrangler/configuration
# - https://developers.cloudflare.com/workers/runtime-apis/bindings
#
# Bindings allow your Worker to interact with resources on the Cloudflare Developer
# Platform (environment variables, databases, assets, secrets, ...).
