name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B Bug:"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## Please provide as many details as possible regarding your bug.
  - type: input
    attributes:
      label: What versions are you using?
      placeholder: 0.0.0 [Wrangler], 0.0.0 [C3], 0.0.0 [Node.js], etc.
    validations:
      required: true
  - type: input
    attributes:
      label: What Operating System are you using?
      placeholder: Mac Sonoma 14.2.1, Windows 11, Linux (or WSL) Debian Bookworm, etc.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the Bug
      description: Please describe the bug and include steps to reproduce. Although not required, we often request a minimal reproduction to help troubleshoot the issue, so providing this up-front streamlines the process towards resolution. Please include any error logs if possible.
    validations:
      required: true
