#:schema node_modules/wrangler/config-schema.json
name = "issue-triager"
main = "src/worker/index.ts"
compatibility_date = "2024-06-14"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "EMBEDDINGS_STORE"
class_name = "EmbeddingsStore"

[[migrations]]
tag = "v1"
new_classes = ["EmbeddingsStore"]

[[vectorize]]
binding = "ISSUES_INDEX"
index_name = "issue-triager-issues-index"