##
# Configuration file for the Asset Server Worker
#
# Please note that Miniflare has a dependency on this Worker.
# Ensure that any configuration changes to this file are persisted in Miniflare as well, when necessary.
# (See packages/miniflare/src/plugins/assets/index.ts -> getAssetService().)
##
name = "asset-server"
main = "src/index.ts"
compatibility_date = "2024-07-31"
