name: Tests + Checks

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  add-to-project:
    if: github.ref != 'refs/heads/changeset-release/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-add-pr
      cancel-in-progress: true
    timeout-minutes: 30
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://devprod-status-bot.devprod.workers.dev/pr-project/workers-sdk/${{ github.event.number }}

  check:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-pr-checks
      cancel-in-progress: true

    name: "Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Build
        run: pnpm run build
        env:
          CI_OS: ${{ runner.os }}

      - name: Check for errors
        # This only runs against markdown files, and so we only need to run prettier checks
        run: pnpm run check:format
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Check the changesets
        run: node -r esbuild-register tools/deployments/validate-changesets.ts

  test:
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.filter }}-test
      cancel-in-progress: true

    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        filter: ["./fixtures/*", "./packages/*", "./tools"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Succeed
        run: "true"
